---
- name: Update QUAY_INDEX_IMAGE_BUILD tag in a YAML file
  hosts: all
  gather_facts: false
  vars:
    target_file: ''
    new_tag_number: ''
    ignore_if_missing: false
  tasks:
    - name: Validate variables
      ansible.builtin.assert:
        that:
          - target_file | length > 0
          - new_tag_number | string is match('^\\d+$')
        fail_msg: "Provide 'target_file' and numeric 'new_tag_number'"

    - name: Ensure file exists
      ansible.builtin.stat:
        path: "{{ target_file }}"
      register: target_stat

    - name: Stop if file is missing (unless ignore_if_missing)
      ansible.builtin.fail:
        msg: "Target file {{ target_file }} does not exist on {{ inventory_hostname }}"
      when:
        - not target_stat.stat.exists
        - not ignore_if_missing

    - name: Update all QUAY_INDEX_IMAGE_BUILD tags (preserve rest of line)
      ansible.builtin.replace:
        path: "{{ target_file }}"
        regexp: "(?m)^(\\s*QUAY_INDEX_IMAGE_BUILD\\s*:\\s*[\"']?.*):([0-9]+)([\"']?\\s*(?:#.*)?\\s*)$"
        replace: "\\1:{{ new_tag_number }}\\3"
        backup: true
      register: replace_result
      when: target_stat.stat.exists

    - name: Fail if no changes were made
      ansible.builtin.fail:
        msg: "No matching QUAY_INDEX_IMAGE_BUILD entries found in {{ target_file }}"
      when:
        - target_stat.stat.exists
        - (replace_result is not defined) or (not replace_result.changed)
        - not ignore_if_missing
